# ===================================================================
# NOTIFICATION SERVICE CONFIGURATION
# Logs completion messages when payment succeeds via RabbitMQ
# ===================================================================

server.port=8085
spring.application.name=notification-service

# --- RabbitMQ Broker Details ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Defines which queue to listen to for notifications
rabbitmq.exchange=payment_exchange
rabbitmq.notification-queue=notification_queue
rabbitmq.notification-routing=notification_routing_key

# Connect to the Service Registry (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
