
server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter

spring.cloud.gateway.routes[2].id=operator-service
spring.cloud.gateway.routes[2].uri=lb://operator-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/operators/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter

spring.cloud.gateway.routes[3].id=recharge-service
spring.cloud.gateway.routes[3].uri=lb://recharge-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/recharges/**
spring.cloud.gateway.routes[3].filters[0]=JwtAuthenticationFilter

spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://payment-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[4].filters[0]=JwtAuthenticationFilter

spring.cloud.gateway.routes[5].id=plans-service
spring.cloud.gateway.routes[5].uri=lb://operator-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/plans/**
spring.cloud.gateway.routes[5].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[5].filters[1]=StripPrefix=2
spring.cloud.gateway.routes[5].filters[2]=PrefixPath=/api/operators/plans

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
