# ===================================================================
# PAYMENT SERVICE CONFIGURATION
# Mock service that finalizes the recharge and saves transactions
# ===================================================================

server.port=8084
spring.application.name=payment-service

# --- Database Details (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/OmniCharge
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

# --- RabbitMQ Configuration ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Where to get payment messages, and where to send notification messages
rabbitmq.exchange=payment_exchange
rabbitmq.payment-queue=payment_queue
rabbitmq.payment-routing=payment_routing_key

rabbitmq.notification-queue=notification_queue
rabbitmq.notification-routing=notification_routing_key

# Connect to the Service Registry (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
