# ===================================================================
# OPERATOR SERVICE CONFIGURATION
# Manages telecom providers and user-purchasable plans.
# ===================================================================

server.port=8082
spring.application.name=operator-service

# --- Database Details (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/OmniCharge
spring.datasource.username=postgres
spring.datasource.password=root

# Keep database tables in sync with Java entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connect to the Service Registry (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
