# ===================================================================
# USER SERVICE CONFIGURATION
# Manages user accounts, authentication, and JWT generation.
# ===================================================================

server.port=8081
spring.application.name=user-service

# --- Database Details (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/OmniCharge
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate ORM config to update tables as classes change
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connect to the Service Registry (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- Security/JWT Details ---
# Provide a matching secret to the one in API Gateway to issue valid tokens
omnicharge.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Tokens expire after 24 hours (86,400,000 milliseconds)
omnicharge.app.jwtExpirationMs=86400000
