# ===================================================================
# RECHARGE SERVICE CONFIGURATION
# Core module handling the start of mobile recharge requests
# ===================================================================

server.port=8083
spring.application.name=recharge-service

# --- Database Details (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/OmniCharge
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- RabbitMQ Message Broker Configuration ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Variables used in code to define where to publish message
rabbitmq.exchange=payment_exchange
rabbitmq.routing.payment=payment_routing_key

rabbitmq.recharge-update-queue=recharge_update_queue

# Connect to the Service Registry (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
